# --- RUNNER --------------------------------------------------------------
runner_id: dl_stpp

# --- DATA -----------------------------------------------------------------
data:
  dataset_name : citibike
  path         : ./data/citibike
  batch_size   : 128
  max_events   : 1024

# --- MODEL ---------------------------------------------------------------
model:
  algorithm    : NeuralSTPP
  hidden_size  : 128
  num_layers   : 2
  dropout      : 0.1
  lr           : 1e-3

# --- TRAINER -------------------------------------------------------------
trainer:
  gpus         : 1
  max_epochs   : 30
  precision    : "16-mixed"
  seed         : 123
  ckpt_dir     : ./checkpoints/citibike_sweep
  save_top_k   : 1
  monitor      : val_loss
  resume_path  : null

# --- LOGGING -------------------------------------------------------------
logging:
  mlflow_uri      : file:./mlruns
  experiment_name : citibike_neural_sweep
  run_name        : sweep_parent

# --- HPO -----------------------------------------------------------------
hpo:
  tuner_id        : ray_tune
  num_trials      : 40
  scheduler       : asha
  resources       : {cpu: 4, gpu: 1}
  results_dir     : ./ray_results/citibike_neural
  experiment_name : citibike_neural_sweep
