# --- RUNNER --------------------------------------------------------------
runner_id: dl_stpp

# --- DATA -----------------------------------------------------------------
data:
  dataset_id : PinwheelHawkes
  batch_size   : 128
  max_events   : 1024

# --- MODEL ---------------------------------------------------------------
model:
    model_id          : "neural_stpp"  # or "att-cnf", "cond_gmm"
    model_sub_id      : "jump-cnf"
    model_config      : "neuralstpp"
    t0                : 0.0
    t1                : 30.0
    dim               :  2
    hdims             : [64, 64, 64]
    tpp_hidden_dims   : [8, 20]
    actfn             :  "softplus"
    tpp_cond          :  False
    tpp_style         : "split"
    tpp_actfn         : "softplus"
    share_hidden      :  False
    solve_reverse     :  False
    l2_attn           :  False
    tol               :  1e-3
    otreg_strength    :  0.0
    tpp_otreg_strength:  0.0
    layer_type        :  "concat"
    naive_hutch       :  False
    lowvar_trace      :  False
    search_space      : 
      lr: {loguniform: [1e-5, 1e-2]}
    warmup_itrs       : 2
    num_iterations    : 10
    momentum          : 0.9
    weight_decay      : 0.0
    gradclip          : 1.0
    max_events        : 100
    data_loaders:
      train_bsz  : 16
      val_bsz    : 64
      test_bsz   : 64
      num_workers: 13
      max_events: 4096
      

# --- TRAINER -------------------------------------------------------------
trainer:
  gpus         : 1
  accelerator  : "mps"
  max_epochs   : 1
  precision    : 32
  seed         : 123
  ckpt_dir     : ./checkpoints/PinwheelHawkesSweep
  save_top_k   : 1
  monitor      : val_loss
  resume_from  : null
  extra_callbacks:
    - class_path: callbacks.common.test_scheduler.TestSchedulerCallback
    - init_args:
        test_every_n_epochs: 5

# --- LOGGING -------------------------------------------------------------
logging:
  mlflow_uri      : ./mlruns
  experiment_name : PinwheelHawkes_neural_sweep
  run_name        : sweep_parent

# --- HPO -----------------------------------------------------------------
hpo:
  tuner_id        : ray_tune
  num_trials      : 1
  scheduler       : asha
  resources       : {cpu: 1}
  results_dir     : ./ray_results/PinwheelHawkesSweep
  experiment_name : PinwheelHawkes_neural_sweep
